.TH SPHERESERVER "6" "April 2025" "sphereserver"
.SH NAME
SphereServer \- Ultima Online server emulator
.SH DESCRIPTION
SphereServer is an Ultima Online server emulator allowing players to run their
own shards.
.SH OPTIONS
.TP
\fB\-H, -?\fR
display command line switches
.TP
\fB\-I\fR=<dir>
set path to ini files.
.TP
\fB\-C\fR
do not use colored console output (default: on).
.TP
\fB\-D\fR
dump global variable DEFNAMEs to defs.txt.
.TP
\fB\-G\fR<dir>
defrags sphere saves.
.TP
\fB\-N\fR<string>
set the sphere name.
.TP
\fB\-P\fR<port>
set the port number.
.TP
\fB\-O\fR<file>
output console to this file name.
.TP
\fB\-Q\fR
quit when finished.
