CONFIGURE_FILE(${CMAKE_CURRENT_LIST_DIR}/ma_config.h.in ${CMAKE_CURRENT_LIST_DIR}/ma_config.h)
CONFIGURE_FILE(${CMAKE_CURRENT_LIST_DIR}/ma_config.h.in ${CMAKE_CURRENT_LIST_DIR}/config.h)
CONFIGURE_FILE(${CMAKE_CURRENT_LIST_DIR}/mariadb_version.h.in ${CMAKE_CURRENT_LIST_DIR}/mariadb_version.h)
