# Generate config.h file for libev (if we are using it)
SET (USE_EV 0)
FOREACH (TARG ${TARGETS})
	GET_TARGET_PROPERTY (DEFS ${TARG} COMPILE_DEFINITIONS)
	FOREACH (DEF ${DEFS})
		IF ("${DEF}" STREQUAL "_LIBEV")
			SET (USE_EV 1)
		ENDIF ("${DEF}" STREQUAL "_LIBEV")
	ENDFOREACH (DEF ${DEFS})
ENDFOREACH (TARG ${TARGETS})

IF (USE_EV)
	INCLUDE ("${CMAKE_CURRENT_SOURCE_DIR}/common/libev/cmake/configure.cmake")
	CONFIGURE_FILE ( "${CMAKE_CURRENT_SOURCE_DIR}/common/libev/cmake/config.h.cmake" "${CMAKE_CURRENT_SOURCE_DIR}/common/libev/config.h" )
ENDIF (USE_EV)
