set(MARIADB_CLIENT_VERSION_MAJOR "10")
set(MARIADB_CLIENT_VERSION_MINOR "8")
set(MARIADB_CLIENT_VERSION_PATCH "7")
set(MARIADB_CLIENT_VERSION_EXTRA "")

set(MARIADB_CLIENT_VERSION
    "${MARIADB_CLIENT_VERSION_MAJOR}.${MARIADB_CLIENT_VERSION_MINOR}.${MARIADB_CLIENT_VERSION_PATCH}${MARIADB_CLIENT_VERSION_EXTRA}"
)
set(MARIADB_BASE_VERSION "mariadb-${MARIADB_CLIENT_VERSION_MAJOR}.${MARIADB_CLIENT_VERSION_MINOR}")
math(
    EXPR
    MARIADB_VERSION_ID
    "${MARIADB_CLIENT_VERSION_MAJOR} * 10000 +
                              ${MARIADB_CLIENT_VERSION_MINOR} * 100   +
                              ${MARIADB_CLIENT_VERSION_PATCH}"
)

set(CPACK_PACKAGE_VERSION_MAJOR 3)
set(CPACK_PACKAGE_VERSION_MINOR 3)
set(CPACK_PACKAGE_VERSION_PATCH 4)

set(CPACK_PACKAGE_VERSION
    "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}"
)
math(
    EXPR
    MARIADB_PACKAGE_VERSION_ID
    "${CPACK_PACKAGE_VERSION_MAJOR} * 10000 +
                            ${CPACK_PACKAGE_VERSION_MINOR} * 100   +
                            ${CPACK_PACKAGE_VERSION_PATCH}"
)

if(NOT MARIADB_PORT)
    set(MARIADB_PORT 3306)
endif()
if(NOT MARIADB_UNIX_ADDR)
    set(MARIADB_UNIX_ADDR "/tmp/mysql.sock")
endif()

set(PROTOCOL_VERSION 10) # we adapted new password option from PHP's mysqlnd !

if(NOT DEFAULT_CHARSET)
    set(DEFAULT_CHARSET "utf8mb4")
endif()

configure_file(${CMAKE_CURRENT_LIST_DIR}/ma_config.h.in ${CMAKE_CURRENT_LIST_DIR}/ma_config.h)
configure_file(${CMAKE_CURRENT_LIST_DIR}/ma_config.h.in ${CMAKE_CURRENT_LIST_DIR}/config.h)
configure_file(${CMAKE_CURRENT_LIST_DIR}/mariadb_version.h.in ${CMAKE_CURRENT_LIST_DIR}/mariadb_version.h)
