MESSAGE (STATUS "Toolchain not specified. Detecting the one to use.")
IF (MSVC)
	INCLUDE ("cmake/toolchains/Windows-MSVC.cmake")
ELSE ()
	IF (APPLE)
			MESSAGE (STATUS "Defaulting to AArch64 (ARM) arch.")
			INCLUDE ("cmake/toolchains/OSX-AppleClang-AArch64.cmake")
	ELSEIF (UNIX)
		IF ("${ARCH}" STREQUAL "x86_64")
			INCLUDE ("cmake/toolchains/Linux-GNU-x86_64.cmake")
		ELSEIF ("${ARCH}" STREQUAL "x86")
			INCLUDE ("cmake/toolchains/Linux-GNU-x86.cmake")
    ELSEIF ("${ARCH}" STREQUAL "arm64")
      INCLUDE ("cmake/toolchains/Linux-Clang-AArch64.cmake")
    ELSE ()
			MESSAGE (STATUS "Unsupported architecture, defaulting to native.")
			INCLUDE ("cmake/toolchains/Linux-GNU-native.cmake")
		ENDIF ()
	ELSE ()
		IF ("${ARCH}" STREQUAL "x86_64")
			INCLUDE ("cmake/toolchains/Windows-GNU-x86_64.cmake")
		ELSEIF ("${ARCH}" STREQUAL "x86")
			INCLUDE ("cmake/toolchains/Windows-GNU-x86.cmake")
		ELSE ()
			MESSAGE (STATUS "Unsupported architecture, defaulting to native.")
			INCLUDE ("cmake/toolchains/Windows-GNU-native.cmake")
		ENDIF ()
	ENDIF ()
ENDIF ()
