name: Nightly build

on: [push, pull_request]

jobs:
  windows-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build 
      run: cmake -G "Visual Studio 17 2022" src/
    - name: Make build
      run: msbuild SphereServer.sln /verbosity:minimal /maxcpucount /p:Configuration=Nightly
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          name: Nightly
          tag_name: Nightly
          files: bin64/Nightly/SphereSvrX64_nightly.exe

  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install -yqq --no-install-recommends curl libmysql++-dev
    - name: CMake
      run: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../src/cmake/toolchains/Linux-GNU-x86_64.cmake -DCMAKE_BUILD_TYPE="Nightly" src/
    - name: Compile spheresvr
      run: make
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          name: Nightly
          tag_name: Nightly
          files: bin64/SphereSvrX64_nightly