name: Upload pull request build

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  windows-64:
    runs-on: windows-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: PR
        path: SphereSvrX-win64-nightly.zip
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-win64-nightly.zip

  windows-32:
    runs-on: windows-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: PR
        path: SphereSvrX-win32-nightly.zip
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-win32-nightly.zip

  linux-64:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: PR
        path: SphereSvrX-linux64-nightly.tar.gz
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-linux64-nightly.tar.gz

  linux-32:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: PR
        path: SphereSvrX-linux32-nightly.tar.gz
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-linux32-nightly.tar.gz