name: Upload Nightly

on: 
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - main

jobs:
  upload-windows-builds:
    runs-on: windows-latest
    steps:
    - name: Download win64 build
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.sha }}
        path: SphereSvrX-win64-nightly.zip
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-win64-nightly.zip

    - name: Download win32 build
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.sha }}
        path: SphereSvrX-win32-nightly.zip
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-win32-nightly.zip

  upload-linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Download linux64 build
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.sha }}
        path: SphereSvrX-linux64-nightly.tar.gz
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-linux64-nightly.tar.gz

    - name: Download linux32 build
      uses: actions/download-artifact@v3
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.sha }}
        path: SphereSvrX-linux32-nightly.tar.gz
    - name: Create pull request tag and upload files
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: Nightly
          tag_name: Nightly
          files: SphereSvrX-linux32-nightly.tar.gz